### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by miki-sol** [B0R9F3D9/Zetachain-earn-xp#2]
![Снимок экрана 2024-02-18 215305](https://github.com/B0R9F3D9/Zetachain-earn-xp/assets/83516414/9cafc5de-51e4-464d-ba79-2923fee6ef0b)
Из за чего возникает данная ошибка?
И может быть у вас есть какой-нибудь тг для связи, чтобы не засорять репортами гитхаб?

**Comment by miki-sol** [comment]
22:03:48 | ERROR   | [№1 - 0x201...E1018] Ответ сервера: 400

И еще вот такая ошибка при попытке клейма

**Comment by B0R9F3D9** [comment]
User not verified это то что ты не сделал регистрацию(енролл) и пытаешься сделать какое-то действие. А execution reverted это транза свара не прошла, мб что-то в настройках не так поставил или увеличь RETRY_COUNT чтобы несколько раз скрипт пробовал сделать транзакции. 400 ошибка тоже то что ты не зарегистрирован.

**Comment by ianaditama26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
deppi4, @ChauChopi, @TheFanatr, @tinhyeuhoagio09, @trandieu554886, @mathshero, @kefentsemcconant848, @sukrucildirr, @wpank, @MOZGIII, @emerylopes, @hknnr, @samparsa1, @nhasan5000, @maiviet262877, @MaintemaGreator, @manami19840419, @yanggaoning0527, @Wolam, @tushujie02tushujie
